### ISSUE TITLE
Build files/instructions

### ISSUE THREAD

**Issue by alokmenghrajani** [square/subzero#11]
Currently, various pieces of the code cannot be built unless people have the exact same HSM hardware. We should support various different builds, including a hardware-less dev/demo build.

Some kind of master build file might also be useful. Perhaps a master Docker file?

**Comment by payomdraftparty** [comment]
```# Add nCipher tools, which unpack to /opt/nfast
WORKDIR /
RUN curl -sSL https://<insert your local url to ncipher-tools>/gccsrc-ppcdev_12.20.51.tar.gz | \
    tar -xz && \
    curl -sSL https://<insert your local url to ncipher-tools>/csd-agg_12.20.51.tar.gz | \
    tar -xz```

Your Dockerfile requires some ncipher URL but makes no reference about what those tools are / where to get them.

**Comment by payomdraftparty** [comment]
I suspect people would want to use aws cloudhsm although i'm not sure how great of an idea that is.

**Comment by mcpherrinm** [comment]
One potentially interesting case would be to use modern Intel features:  Secureboot & SGX provide a lot of the benefits of SEE but in a readily available off-the-shelf platform.  It's not something I'm familiar with right now but I think it ought to be plausible.

**Comment by alokmenghrajani** [comment]
My goal is to improve the build files so people can at least have a dev/demo environment on their personal machines. This would then enable anyone to get their specific hardware (SGX, another HSM vendor, or something else) to work.

Over time, we might end up with a tool which supports many different hardware.

**Comment by haarts** [comment]
There seems no way to get the `ncipher-tools` w/o being a customer of Thales. Is that correct?

**Comment by alokmenghrajani** [comment]
Correct. We are currently in the following state:
- Anyone can build the Core (C code). The code however does not implement a secure cipher and does not implement proper key protection when used outside a HSM (not using a HSM is only supported for dev/demo purpose)
- You cannot build the Java code (we still need to port our Java build files to maven and make the nCipher dependency optional).
- Building the DVD currently requires commenting out some parts of the build script.

**Comment by alokmenghrajani** [comment]
Short update:
Over the last few days, we added build files and fixed many minor bugs. It should now be possible for anyone to build the C and Java pieces. The code should work whether you own the same HSM or not. There's also a server, to help create and debug QR the codes.

Over the next few days, we are going to document how to build and test things. We eventually also want to include a `demo.iso` which anyone will be able to run in a VM or on real hardware; without having to compile all the various parts.

**Comment by payomdraftparty** [comment]
This is great, thank you!

**Comment by payomdraftparty** [comment]
This is great, thank you!

**Comment by alokmenghrajani** [comment]
https://github.com/square/subzero/pull/69 addresses the lack of documentation. I'm going to keep adding more docs over time (e.g. how to go from xpubs to signing a transaction) as well as include some additional info (what are testnet faucets, how to broadcast testnet transactions, etc.).

I however think we are now in better shape and I'm going to close this issue.

**Comment by alokmenghrajani** [comment]
@haarts @payomdraftparty: I should have clarified. The docs now explain how to run the project without using any HSM. This is useful to try things out or for dev purpose.

Please let me know if you need any additional info?

**Comment by payomdousti** [comment]
cool, thanks!
