### ISSUE TITLE
issues trying to build/boot dvd

### ISSUE THREAD

**Issue by alokmenghrajani** [square/subzero#191]
@alokmenghrajani unclear what the centos root username and password are, is it just `root` with one of the passwords in https://github.com/square/subzero/blob/master/live-usb-creator/rhel7-livemedia.ks?

Also noticed the top of that file says "DEVEL" - outside of changing username/password, anything you'd recommend to be changed for production?

_Originally posted by @bosswissam in https://github.com/square/subzero/issues/14#issuecomment-613093692_

**Comment by alokmenghrajani** [comment]
https://github.com/square/subzero/issues/14#issuecomment-613221727

> Hm interesting.
> 
> I'm trying to boot a VMware Fusion machine from the iso, and it won't take `root` as username (immediately re-prompts) (screencapture: https://app.box.com/s/p0wl8km16iica8dwtzqqnsyj8xlh5ucy).
> 
> I can't boot-up the VM from the USB stick because Mac can no longer read the device after I ran the `dd` command to copy over the iso - is that normal? The device was in FAT32 to start. Actually seems even if I don't use `dd`, VMware fusion can't boot from a USB anyway.
> 
> Using this for testing before I go ahead and buy dedicated hardware.

The iso is a Joliet filesystem (see https://github.com/square/subzero/blob/master/live-usb-creator/patches/usr/share/lorax/live/x86.noeverything.tmpl#L95), there is no fat32 involved.

Mac OS X typically doesn't recognize the iso (see https://askubuntu.com/questions/153833/why-cant-i-mount-the-ubuntu-12-04-installer-isos-in-mac-os-x, I think it's the same issue, but I could be wrong since that's from 4 years ago). You can make it work on Mac OS X by dropping the isohybrid part (or picking up the patch for isohybrid if that's the issue).

I personally prefer being able to boot off USB -- I have never had a need to mount the iso on Mac OS X.

**Comment by bosswissam** [comment]
@alokmenghrajani gotcha.

If I may ask, for development purposes, are you connecting the HSM via an external PCIe card enclosure or you actually have a laptop/server with enough space to fit an HSM?

Plenty of options to buy but would rather go with what is known to work.

**Comment by bosswissam** [comment]
@alokmenghrajani trying this again on a lenovo machine, it is able to recognize and boot from the USB, however, it runs into the same problem: it prompts for login and does not take `root` for an answer - same as what I saw when using VMware to run the `boot.iso` file: https://app.box.com/s/p0wl8km16iica8dwtzqqnsyj8xlh5ucy

**Comment by bosswissam** [comment]
but using `liveuser` worked (just saw your [comment](https://github.com/square/subzero/issues/14#issuecomment-613164866))
