### ISSUE TITLE
InitWallet.java incorrectly sets currency to Wallet.Currency.TEST_NET

### ISSUE THREAD

**Issue by alokmenghrajani** [square/subzero#254]
`.setCurrency(Wallet.Currency.TEST_NET)` is incorrect.

We probably need to add a currency flag to InitWalletRequest and then make sure we use the proper currency everywhere.

**Comment by ivmaykov** [comment]
I think we don't necessarily need a flag. The wallet creation happens in two steps (init wallet, finalize wallet). And the internal FinalizeWalletResponse returns a plaintext pub key. We should be able to parse that pub key using bitcoinj and infer the currency from that (if I understand correctly, if the plaintext pub key begins with "xpub..." then the currency is MAIN_NET, if it begins with "tpub..." then the currency is TEST_NET, etc. But we don't need to be quite so simplistic, we can parse the key with bitcoinj and then check what bitcoin network the key belongs to). Then we can just overwrite the currency field of the wallet during the finalize stage before we save it back to disk.

CC @andozw @oreparaz what do you guys think of this approach?

**Comment by ivmaykov** [comment]
This is fixed in https://github.com/square/subzero/pull/693
