### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by payomdraftparty** [square/subzero#26]
```CURRENCY=btc-testnet cmake ../``` 

fails because subdirectory trezor-crypto is missing.

**Comment by payomdraftparty** [comment]
also cloning the trezor-crypto project into subzero/core throws an issue that the trezor-crypto project doesn't have a CMakeLists.txt file.

**Comment by payomdraftparty** [comment]
git submodules isn't working automatically since the .gitmodules file isn't in the top level dir along with .git.

In any case, even when cloning down the correct dependencies, I still get

```
CMake Error at CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /Code/subzero/core/trezor-crypto

  does not contain a CMakeLists.txt file.
```

**Comment by mcpherrinm** [comment]
Hmm looks like they deleted it upstream and we forked to re-introduce it, which didn't make it to our github release.

**Comment by alokmenghrajani** [comment]
CMakeLists.txt exists in trezor-crypto if you checkout the right version: https://github.com/trezor/trezor-crypto/blob/2e528be1e91dd48c0e55061fbdd40ccf8b285559/CMakeLists.txt

I'm currently working on improving our build story (see https://github.com/square/subzero/issues/11).

**Comment by alokmenghrajani** [comment]
https://github.com/square/subzero/pull/37 should have helped with this issue.
