### ISSUE TITLE
can't find validation.proto

### ISSUE THREAD

**Issue by zebpaypeswani** [square/subzero#33]
Hi I am getting error at service.proto `import "subzero/common/validation.proto";` it could not find validation.proto. The project structure is little bit confusing would be great if we can use gradle.

**Comment by alokmenghrajani** [comment]
Good catch. validation.proto needs to be removed. I'll make a PR.

**Comment by zebpaypeswani** [comment]
Hi Alok when can I expect PR. thanks

**Comment by alokmenghrajani** [comment]
I'm planning to improve the build over the next several months. Sorry if this timeline sounds longer than expected, there's a bunch of improvements that need to be addressed.

**Comment by zebpaypeswani** [comment]
Thanks for the stats, in the mean time can you please upload missing files. So that at least I can compile the project. thanks!

**Comment by alokmenghrajani** [comment]
There is no missing file. Just remove the reference to validation.proto and you should be all set.

**Comment by alokmenghrajani** [comment]
https://github.com/square/subzero/issues/11 tracks our effort to improve the build story.
