### ISSUE TITLE
Document how to use nCipher in dev over SSH

### ISSUE THREAD

**Issue by mbyczkowski** [square/subzero#87]
HSM initialization page should explain how to:
- create a wrapper script
- set port forwarding
- select nCipherKM.jar lib (has to be in the right directory) over the fake ncipher
- set `/opt/kmdata/local` on the dev machine so that it's in sync with nCipher machine
- set required config options in the YAML file

**Comment by alokmenghrajani** [comment]
https://github.com/square/subzero/pull/195
