### ISSUE TITLE
Potential post bitcoinj 0.15 cleanup

### ISSUE THREAD

**Issue by alokmenghrajani** [square/subzero#95]
https://github.com/square/subzero/pull/94 bumps the version of bitcoinj to 0.15.2.

It might now be possible to delete [createWrappedSegwitMultisigTransaction](https://github.com/square/subzero/blob/master/java/shared/src/main/java/com/squareup/subzero/shared/ColdWallet.java#L136). This was needed as a workaround due to the lack of Segwit support in bitcoinj -- which was added in 0.15.

note: we might still need bits and pieces of createWrappedSegwitMultisigTransaction if Bitcoinj doesn't support segwit + multisig, but we might be able to at least simplify things a little.

**Comment by andoct** [comment]
Unfortunately, bitcoinj still doesn't support creating and spending from p2wsh. Only parsing/validation logic.

**Comment by alokmenghrajani** [comment]
Good to know. I'll close this and we can re-open once bitcoinj has the right support. We create p2sh-p2wsh transactions.
